"""empty message

Revision ID: 0190f7a5e7c7
Revises: cf378ff50128
Create Date: 2023-12-17 15:32:01.415172

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0190f7a5e7c7'
down_revision = 'cf378ff50128'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.drop_constraint('error_log_ibfk_2', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('error_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('error_log_ibfk_2', 'users', ['user_id'], ['user_id'], ondelete='CASCADE')

    # ### end Alembic commands ###
