"""empty message

Revision ID: cf378ff50128
Revises: 27ac11e61764
Create Date: 2023-12-15 15:45:15.185569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf378ff50128'
down_revision = '27ac11e61764'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('built_in_role', schema=None) as batch_op:
        batch_op.add_column(sa.Column('have_document_store', sa.Boolean(), server_default=sa.text('TRUE'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('built_in_role', schema=None) as batch_op:
        batch_op.drop_column('have_document_store')

    # ### end Alembic commands ###
