"""empty message

Revision ID: e44885aa3a0b
Revises: 0190f7a5e7c7
Create Date: 2023-12-18 22:02:05.498956

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e44885aa3a0b'
down_revision = '0190f7a5e7c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('head_portrait', schema=None) as batch_op:
        batch_op.drop_index('path')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('head_portrait', schema=None) as batch_op:
        batch_op.create_index('path', ['path'], unique=False)

    # ### end Alembic commands ###
